### ISSUE TITLE
Can I publish the rtmp-stream and rtmfp-stream with the same way.

### ISSUE THREAD

**Issue by losywee** [OpenRTMFP/ArcusNode#18]
Can I publish the rtmp-stream and rtmfp-stream with the same way. Thanks.

**Comment by thomasjammet** [comment]
Hi Losywee,

You should use [MonaServer](http://www.monaserver.ovh/), it supports RTMP, RTMFP, HTTP and WebSocket protocols and it is often updated.

Regards

**Comment by losywee** [comment]
Thanks.
